### ISSUE TITLE
[BUG] Compile error on nightly Rust in-line ASM code

### ISSUE THREAD

**Issue by luojia65** [mattgodbolt/compiler-explorer#1554]
**Describe the bug**
Compile failed when my code includes Rust in-line ASM code. There is no any lines of detailed compile error output, only showing a red `X` mark. 
When try to trigger compiler output, it shows like this: 
```
error[E0602]: unknown lint: `l,_rpath,/opt/compiler_explorer/rust_nightly/lib`
  |
  = note: requested on the command line with `-W l,_rpath,/opt/compiler_explorer/rust_nightly/lib`

error[E0602]: unknown lint: `l,_rpath,/opt/compiler_explorer/rust_nightly/lib32`
  |
  = note: requested on the command line with `-W l,_rpath,/opt/compiler_explorer/rust_nightly/lib32`

error[E0602]: unknown lint: `l,_rpath,/opt/compiler_explorer/rust_nightly/lib64`
  |
  = note: requested on the command line with `-W l,_rpath,/opt/compiler_explorer/rust_nightly/lib64`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0602`.
```

**To Reproduce**
Switch compiler type to nightly Rust, then input these code:
```Rust
#![feature(asm)]

pub fn nop() {
    asm!("nop");
}
```

**Expected behavior**
This code should generate properly to a Rust-convention function wrapper with one line of `nop` instructuction inside.

**Comment by partouf** [comment]
I assume this error was produced locally and not on the live website? Only in binary and execution mode should this error occur, and it was fixed with this commit https://github.com/mattgodbolt/compiler-explorer/commit/41f696489d6787b2b5b3fffc8b52582ae7547ad8

So please try again with the latest source.

**Comment by luojia65** [comment]
@partouf I am afraid it still occurs on the website. FYI I shared my code and configuration here: https://godbolt.org/z/5y-ZHn

**Comment by partouf** [comment]
When clicking the above link, I get a very different error because of unsafeness.

![image](https://user-images.githubusercontent.com/442630/63699922-151a5000-c822-11e9-81f8-5e572e162a5c.png)

**Comment by luojia65** [comment]
Wow, I checked again and this code could compile now (after `unsafe` fixed). Thanks a lot! :) @partouf
